create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_name text not null check (event_name in (
    'catalog_opened',
    'first_item_added',
    'order_summary_opened',
    'order_submitted',
    'template_used',
    'history_order_used'
  )),
  actor_key text not null check (char_length(actor_key) = 64),
  session_id uuid not null,
  journey_id uuid not null,
  device_type text not null default 'unknown' check (device_type in ('mobile', 'tablet', 'desktop', 'unknown')),
  source text check (source is null or source in ('catalog', 'template', 'history', 'latest_order')),
  item_count integer check (item_count is null or (item_count >= 0 and item_count <= 10000)),
  created_at timestamptz not null default now()
);

create index if not exists analytics_events_created_at_idx
  on public.analytics_events (created_at desc);

create index if not exists analytics_events_event_created_idx
  on public.analytics_events (event_name, created_at desc);

create index if not exists analytics_events_actor_created_idx
  on public.analytics_events (actor_key, created_at desc);

create index if not exists analytics_events_journey_created_idx
  on public.analytics_events (journey_id, created_at asc);

alter table public.analytics_events enable row level security;

revoke all on table public.analytics_events from public, anon, authenticated;
revoke all on sequence public.analytics_events_id_seq from public, anon, authenticated;

comment on table public.analytics_events is
  'Pseudonymized ordering funnel events. No names, emails, order IDs, product IDs, IP addresses or user-agent strings are stored.';
